# Generated by Django 3.1.2 on 2020-10-13 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ingresa la categoría.', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa tu nombre.', max_length=15)),
                ('apellidos', models.CharField(help_text='Ingresa tus apellidos.', max_length=30)),
                ('telefono', models.IntegerField(help_text='Ingresa tu número de teléfono.')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta reserva.', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('e', 'Entregado'), ('p', 'Pendiente'), ('c', 'Cancelada')], default='p', help_text='Estado del pedido.', max_length=1)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.articulo')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.cliente')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ManyToManyField(help_text='Selecciona una categoria.', to='catalogo.Categoria'),
        ),
    ]
