# Generated by Django 3.1.2 on 2020-10-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201013_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(help_text='Ingresa tus apellidos.', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Ingresa tu nombre.', max_length=30),
        ),
    ]
