# Generated by Django 3.1.2 on 2020-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201013_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, choices=[('e', 'Entregado'), ('p', 'Pendiente'), ('c', 'Cancelada'), ('n', 'No disponible')], default='p', help_text='Estado del pedido.', max_length=1),
        ),
    ]
