# Generated by Django 3.1.2 on 2020-10-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201013_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Ingresa la cantidad que quieres.'),
        ),
    ]
