# Generated by Django 3.1.2 on 2020-10-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_reserva_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha_reserva']},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha',
            new_name='fecha_reserva',
        ),
    ]
